# Generated by Django 4.1 on 2022-08-06 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Ativo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=6)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.empresa')),
            ],
        ),
    ]
