# Generated by Django 4.1 on 2022-08-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0004_alter_ativo_codigo_alter_empresa_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
