# Generated by Django 4.1 on 2022-08-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0005_alter_ativo_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='codigo',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='codigo',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
