# Generated by Django 4.1 on 2022-08-08 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0006_alter_ativo_codigo_alter_empresa_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ativo',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cotacao.empresa'),
        ),
    ]
