# Generated by Django 4.1 on 2022-08-08 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0008_alter_ativo_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.ativo')),
            ],
        ),
        migrations.CreateModel(
            name='AtivoMonitorado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('preco_compra', models.FloatField()),
                ('preco_venda', models.FloatField()),
                ('intervalo_consulta', models.IntegerField()),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cotacao.ativo')),
            ],
        ),
    ]
